language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./main.py
  - python -m compileall ./cogs
  - python -m compileall ./utils
after_success:
  - wget https://raw.githubusercontent.com/lyricalpaws/travisCI-discord-embed/main/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/lyricalpaws/travisCI-discord-embed/main/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL